server:
  port: 8080



  #========Mybatis-plus配置==========
  ---
  mybatis-plus:
    mapper-locations: classpath*:/mapper/*Mapper.xml
    global-config:
      id-type: 2
      field-strategy: 2
      auto-set-db-type: true
      db-column-underline: true
      refresh-mapper: true
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
